/**
 * Paths of the Rare Legacy logo files. Kept free of imports so next.config.ts
 * can read it too. See src/lib/brand.ts for how the site uses them.
 */
export const BRAND_DIR = "/brand/rare-legacy";

export const BRAND_FILES = {
  /** Full logo: symbol, "Rare Legacy" script and "LIFE GROUP". */
  logoBlackSvg: `${BRAND_DIR}/rare-legacy-logo-black-transparent.svg`,
  logoCreamSvg: `${BRAND_DIR}/rare-legacy-logo-cream-transparent.svg`,
  logoBlackPng: `${BRAND_DIR}/rare-legacy-logo-black-transparent.png`,
  logoCreamPng: `${BRAND_DIR}/rare-legacy-logo-cream-transparent.png`,
  logoBlackOnCreamPng: `${BRAND_DIR}/rare-legacy-logo-black-on-cream.png`,
  logoCreamOnBlackPng: `${BRAND_DIR}/rare-legacy-logo-cream-on-black.png`,
  /** Symbol only: the infinity with the gem. */
  symbolBlackSvg: `${BRAND_DIR}/rare-legacy-symbol-black-transparent.svg`,
  symbolCreamSvg: `${BRAND_DIR}/rare-legacy-symbol-cream-transparent.svg`,
  symbolBlackPng: `${BRAND_DIR}/rare-legacy-symbol-black-transparent.png`,
  symbolCreamPng: `${BRAND_DIR}/rare-legacy-symbol-cream-transparent.png`,
  /** Generated by scripts/prepare-logo-assets.mjs: 1200x630, full logo on cream. */
  shareImage: "/brand/rare-legacy-share.png",
} as const;

/**
 * Old public logo URLs (they may be in emails already sent or cached by social
 * sites). Each one now redirects to the matching new file.
 */
export const LEGACY_BRAND_REDIRECTS: ReadonlyArray<readonly [string, string]> = [
  ["/brand/logo-dark-horizontal.png", BRAND_FILES.logoCreamPng],
  ["/brand/logo-dark-stacked.png", BRAND_FILES.logoCreamPng],
  ["/brand/logo-light-stacked.png", BRAND_FILES.logoBlackPng],
  ["/brand/icon-dark.png", BRAND_FILES.symbolCreamPng],
  ["/brand/icon-light.png", BRAND_FILES.symbolBlackPng],
];
